runtime: python311

entrypoint: gunicorn -b :$PORT commerce.wsgi

env_variables:
    DJANGO_SETTINGS_MODULE: "commerce.settings"
    DATABASE_URL: "sqlite:////tmp/db.sqlite3"
    ENV: "production"

instance_class: F1
automatic_scaling:
  min_instances: 0
  max_instances: 2
  target_cpu_utilization: 0.8
  min_pending_latency: automatic
  max_pending_latency: automatic

handlers:
- url: /static
  static_dir: static/

- url: /.*
  script: auto
