# Generated by Django 4.1.3 on 2022-12-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing_comments_bids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Cars', 'Cars'), ('Appliances', 'Appliances'), ('Sports', 'Sports')], default=1, max_length=64),
        ),
    ]
