# Generated by Django 4.1.3 on 2022-12-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_alter_bids_bidamount_alter_bids_currentbid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='bidAmount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bids',
            name='currentBid',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
