# Generated by Django 4.1.3 on 2022-12-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_alter_bids_currentbid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='bidAmount',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
