# Generated by Django 4.1.3 on 2022-12-22 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_alter_bids_user_bidder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='user_bidder',
        ),
    ]
