# Generated by Django 4.1.3 on 2022-12-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_remove_bids_user_bidder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='category',
            field=models.CharField(choices=[('Car', 'Car'), ('Appliances', 'Appliances'), ('Equipment', 'Equipment'), ('Clothing', 'Clothing'), ('Kids Stuff', 'Kids Stuff'), ('No Category', 'No Category')], default='No Category', max_length=45),
        ),
    ]
