# Generated by Django 4.1.3 on 2022-12-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0026_alter_listings_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='category',
            field=models.CharField(choices=[('No Category', 'No Category'), ('Car', 'Car'), ('Appliances', 'Appliances'), ('Equipment', 'Equipment'), ('Clothing', 'Clothing'), ('Kids Stuff', 'Kids Stuff')], default='No Category', max_length=64),
        ),
    ]
