# Generated by Django 4.1.3 on 2022-12-31 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0027_alter_listings_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='currentHighestBidder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='get_current_highest_bidder', to=settings.AUTH_USER_MODEL),
        ),
    ]
