# Generated by Django 4.1.3 on 2022-12-08 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='buyer',
            field=models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='get_buyer_listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
