# Generated by Django 4.1.3 on 2022-12-08 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_listing_buyer_alter_listing_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Listing',
            new_name='Listings',
        ),
    ]
