# Generated by Django 4.1.3 on 2022-12-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_listings_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='category',
            field=models.CharField(choices=[('Sports', 'Sports'), ('Appliances', 'Appliances'), ('Cars', 'Car')], default='Cars', max_length=64),
        ),
    ]
