# Generated by Django 4.1.3 on 2022-12-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_alter_bids_currentbid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='bidAmount',
            field=models.FloatField(default=10),
        ),
        migrations.AlterField(
            model_name='bids',
            name='currentBid',
            field=models.FloatField(blank=True, default=10, null=True),
        ),
    ]
