# Generated by Django 4.1.3 on 2022-12-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_alter_bids_bidamount_alter_bids_currentbid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='currentBid',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
