# Generated by Django 4.1.3 on 2022-12-19 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_remove_listings_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='user_bidder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_user_bids', to=settings.AUTH_USER_MODEL),
        ),
    ]
